### ISSUE TITLE
Is this line should be changed?

### ISSUE THREAD

**Issue by russ-spec** [BBuf/how-to-optim-algorithm-in-cuda#1]
https://github.com/BBuf/how-to-optim-algorithm-in-cuda/blob/3c2fc8b30d211628228e1b9018e23e920f13eed0/reduce/reduce_v1_interleaved_addressing.cu#L24

Is this line should be changed?  ` sdata[tid] += sdata[tid + s];` -> ` sdata[index] += sdata[index + s];`

**Comment by BBuf** [comment]
> https://github.com/BBuf/how-to-optim-algorithm-in-cuda/blob/3c2fc8b30d211628228e1b9018e23e920f13eed0/reduce/reduce_v1_interleaved_addressing.cu#L24
> 
> Is this line should be changed? ` sdata[tid] += sdata[tid + s];` -> ` sdata[index] += sdata[index + s];`

fixed, thanks!
