### ISSUE TITLE
error: more than one conversion function from "half" to a built-in type applies:

### ISSUE THREAD

**Issue by GeneralJing** [BBuf/how-to-optim-algorithm-in-cuda#10]
atomic_add_half.cu(18): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(204): here
            function "__half::operator short() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(222): here
            function "__half::operator unsigned short() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(225): here
            function "__half::operator int() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(228): here
            function "__half::operator unsigned int() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(231): here
            function "__half::operator long long() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(234): here
            function "__half::operator unsigned long long() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(237): here
            function "__half::operator __nv_bool() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(241): here

atomic_add_half.cu(18): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(204): here
            function "__half::operator short() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(222): here
            function "__half::operator unsigned short() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(225): here
            function "__half::operator int() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(228): here
            function "__half::operator unsigned int() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(231): here
            function "__half::operator long long() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(234): here
            function "__half::operator unsigned long long() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(237): here
            function "__half::operator __nv_bool() const"
/usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp(241): here

atomic_add_half.cu(21): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (half *, half)

3 errors detected in the compilation of "atomic_add_half.cu".
编译atomic_add_half.cu的时候报错了，是需要指定什么参数编译吗？

**Comment by Carem2Dir** [comment]
可以试试这个 "nvcc -arch=sm_80"

**Comment by GeneralJing** [comment]
多谢大佬，可以了
