### ISSUE TITLE
有关lecture14后半部分faster matmul的一些小疑问

### ISSUE THREAD

**Issue by PaoChaHuPao** [BBuf/how-to-optim-algorithm-in-cuda#11]
您好我想请教一个小问题:
结合之前的matmul的优化,这里后面的triton中和之前讲到的tiling(分块)是一样的吗?
ipynb中演示的时候说的是将row为主的读取方式改变为分块按column读取
但是我个人这里感觉有点脱裤子放屁的意思了:
这不就是改变了读取数据的方式来实现类似于lecture5 中自己使用shared mem实现的matmul版本;
而且我去翻看了triton的官方文档中的描述,感觉对于这个问题triton的描述十分的别扭;
还是说这里是和triton中的实现有关?导致如果使用triton来实现tiling得按照这样的过程
学艺不精,如有纰漏,还请见谅

**Comment by cemamxiaoxixi** [comment]
您的邮件我已经收到，会尽快回复的。

**Comment by BBuf** [comment]
> 您好我想请教一个小问题: 结合之前的matmul的优化,这里后面的triton中和之前讲到的tiling(分块)是一样的吗? ipynb中演示的时候说的是将row为主的读取方式改变为分块按column读取 但是我个人这里感觉有点脱裤子放屁的意思了: 这不就是改变了读取数据的方式来实现类似于lecture5 中自己使用shared mem实现的matmul版本; 而且我去翻看了triton的官方文档中的描述,感觉对于这个问题triton的描述十分的别扭; 还是说这里是和triton中的实现有关?导致如果使用triton来实现tiling得按照这样的过程 学艺不精,如有纰漏,还请见谅

这里和官方教程应该是一致的，可以参考：https://mp.weixin.qq.com/s/RMR_n1n6nBqpdMl6tdd7pQ
