### ISSUE TITLE
The length of the output will be halved

### ISSUE THREAD

**Issue by yizhibaiwuya** [BBuf/how-to-optim-algorithm-in-cuda#3]
https://github.com/BBuf/how-to-optim-algorithm-in-cuda/blob/457fedd8a5849b2da9a28fe4f3697d0d063e4b94/reduce/reduce_v3_idle_threads_free.cu#L36

In reduce_v3_idle_threads_free.cu, each block is responsible for the reduction of 512 elements. However, this will result in the final output length being halved.  But this is contrary to our desire to reduce every 256 elements.

**Comment by BBuf** [comment]
<img width="586" alt="图片" src="https://github.com/BBuf/how-to-optim-algorithm-in-cuda/assets/35585791/67ed1d4d-b746-44d5-bb85-768a84323ee5">
