### ISSUE TITLE
minor error in reduction part

### ISSUE THREAD

**Issue by edmond419** [BBuf/how-to-optim-algorithm-in-cuda#4]
Hi, thanks for your sharing. However, there is a little mistake in your reduction part. The interleave addressing section. It should be sdata[index] += sdata[index + s] instead of sdata[tid] += sdata[tid+s]

reference: https://developer.download.nvidia.com/assets/cuda/files/reduction.pdf
page 11

**Comment by BBuf** [comment]
fixed now, thank you!
