### ISSUE TITLE
reduce: memcpy bug not fix in README

### ISSUE THREAD

**Issue by pingzhuu** [BBuf/how-to-optim-algorithm-in-cuda#5]
[Code ](https://github.com/BBuf/how-to-optim-algorithm-in-cuda/commit/90e431347c22339df1c614eb69deebf8dce264db) fixed 

[README](https://github.com/BBuf/how-to-optim-algorithm-in-cuda/blob/master/reduce/README.md) not fix

![image](https://github.com/BBuf/how-to-optim-algorithm-in-cuda/assets/58718936/193cc8ac-84b9-46da-be0f-c8ca1d6c1f78)

**Comment by BBuf** [comment]
fixed! thanks.
